name: Test repository dispatch
on:
  repository_dispatch:
    types: [update-version]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.VERSION_NUMBER }}